### ISSUE TITLE
(question) Pinch events not firing consistently when setting a property

### ISSUE THREAD

**Issue by mattboldt** [chriswessels/ember-hammer#11]
I'm using `pinchin` and `pinchout` and am running into a weird problem

```
# View
  zf: Em.computed.alias('controller.documentController.zoomFactor')
  gestures:
    pinchin: (e) ->
      zoomAmount = @get('zf') * e.gesture.scale
      @get('controller.documentController').pinchZoom(zoomAmount)
      false
```

```
# Controller
  pinchZoom: (zoomAmount) ->
    return false if zoomAmount < 0 || zoomAmount > 10
    Em.run.throttle @, ->
      @set('zoomFactor', zoomAmount)
      return false
    , 200
```

If I begin pinching in the middle of the view, a _single_ event is fired per pinch. If I begin pinching on the edges of the screen, events get fired consistently. I've tried moving it to different views to see if it's a bubbling problem, but no luck.

If I remove the `@set('zoomFactor', zoomAmount)` line, all events are fired consistently.

**Comment by mattboldt** [comment]
Never mind... It was an event bubbling issue. I had a child div in my view preventing the pinch to keep pinching.

**Comment by chriswessels** [comment]
Thanks for closing @mattboldt!

**Comment by mattboldt** [comment]
However, I am having an issue setting the `tap` event's `taps` property to 2. Currently it fires for just one tap. Shouldn't this do it?

```
hammerOptions:
    tap_taps: 2

gestures:

    pinchin: (e) ->
    # etc

```

**Comment by chriswessels** [comment]
@mattboldt, try:
```
hammerOptions:
    tap:
        taps: 2
```
