### ISSUE TITLE
Events are called twice in Ember 1.13.10

### ISSUE THREAD

**Issue by rogatty** [chriswessels/ember-hammer#13]
https://github.com/chriswessels/ember-hammer/pull/12 was needed to make ember-hammer work with Ember v1.13.5 (at least that was the version we were using). After upgrading to Ember v1.13.10 touch events started to be called twice. There had to be some change in Ember that made https://github.com/chriswessels/ember-hammer/pull/12 useless for the latest version (probably not just this one).

As a quick fix we've downgraded ember-hammer to v1.0.0.

**Comment by chriswessels** [comment]
Resolved by #14
